### ISSUE TITLE
carriage return when read diffuse texture name

### ISSUE THREAD

**Issue by Cewein** [syoyo/tinyobjloader-c#19]
On windows and with VS, reading the texture name return a carriage return, texture cannot be properly loaded in some cases.

**Comment by syoyo** [comment]
>  texture cannot be properly loaded in some cases.

Could you please post minimal, reproducable .mtl file?

**Comment by Cewein** [comment]
here the file :
```
# Blender MTL File: 'JUPITER.blend'
# Material Count: 1

newmtl JUPITER
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.640000 0.640000 0.640000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 0.362319
illum 1
map_Kd 2k_jupiter.jpg 

```

this is how I read the name after loading in the file

```c
printf("name of diffuse tex : %s",materials->diffuse_texname));
```
to solve the problem i must use 

```c
char * removeEnter(char * text)
{
	int i = 0;
	printf("\n");
	while (text[i] != '\n')
	{
		printf("indice %d : %c\n", i, text[i]);
		i++;
	}
	text[i] = '\0';
	return text;
}
```

I use stb_image.h to load the file, if you want to know more, tell me

**Comment by Cewein** [comment]
> I've encountered this, it happens when the obj file is saved with CRLF endings. In mttllib-statements, the CR at the end of the line is considered part of the mtl filename. Converting the obj file to LF fixes the problem (using dos2unix, or any text-editor).
> 
> EDIT: Realized Cewein's problem is slightly different, but both probably have the same cause.

Yes just test your solution, it work, save it from saving with CRLF endings make the texture impossible to load.

**Comment by syoyo** [comment]
Fixed and I have added regression test here:

https://github.com/syoyo/tinyobjloader-c/blob/master/test/tinyobj_regression_tests.c#L8
