### ISSUE TITLE
[TODO] Support reading line larger than 8192 bytes

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyobjloader-c#20]
Currently max bytes per line are limited to 8192.

Support arbitrary bytes per line.

**Comment by mandyedi** [comment]
Hi @syoyo
I'd like to contribute to your obj loader. How would you like to extend the buffer for reading lines? I was thinking reallocating the buffer if it exceeds the 8192 limit. Or maybe getline could be used instead of fgets, but I'm not sure of its compatibility with C98.

**Comment by syoyo** [comment]
@mandyedi Awesome!

One possible solution is dynamically grow buffer while reading data using `fgets`

https://ossguy.com/?p=284

Another and more robust solutions is first read whole data from a file, then find line endings as done in multi-threaded .obj parser: https://github.com/syoyo/tinyobjloader/tree/master/experimental

**Comment by mandyedi** [comment]
Thanks for the suggestions! To keep it simple and C compatible I choose the dynamic buffer solution.
