### ISSUE TITLE
Material name corruption in tinyobj_parse_obj

### ISSUE THREAD

**Issue by PeterOGB** [syoyo/tinyobjloader-c#34]
When constructing a null terminated version of the material name, the last character is being overwritten due to wrong character index being used .
Line 1379:
material_name_null_term[commands[i].material_name_len-1] = 0;
should be 
material_name_null_term[commands[i].material_name_len] = 0;

**Comment by syoyo** [comment]
Good catch!

Your PR has been merged https://github.com/syoyo/tinyobjloader-c/pull/35 , so I think this issue is ready to close.
