### ISSUE TITLE
Infinite loop in hash table inserting when reading mtl file

### ISSUE THREAD

**Issue by Sharlock93** [syoyo/tinyobjloader-c#52]
The `hash_table_insert_value` hits an infinite loop if the `capacity` is 10 and the `start_index` is 9, the `(i*i)` addition doesn't produce every possible index and in my case unfortunately it so happens that every index it produces were filled, here is a simple log:
```c
|| ===============
|| start index 9 index 9
|| i : 1) new index 0
|| i : 2) new index 3
|| i : 3) new index 8
|| i : 4) new index 5
|| i : 5) new index 4
|| i : 6) new index 5
|| i : 7) new index 8
|| i : 8) new index 3
|| i : 9) new index 0
|| ===============
```

here are the files to reproduce this:
[car.zip](https://github.com/syoyo/tinyobjloader-c/files/8735385/car.zip)

changing `i*i` to a simple `i` fixes this.

No clue if it has been reported before.

**Comment by syoyo** [comment]
Reading `car.obj` with `viewer` https://github.com/syoyo/tinyobjloader-c/tree/master/examples/viewer does not go infinite loop.

Please post reproducible code and procedure.

**Comment by Sharlock93** [comment]
> Please post reproducible code and procedure.

this is my main and nothing else:
```c
int main() {

	// sh_obj_mesh_t mesh = sh_read_obj_mesh("assets/cw1/car.obj");

	tinyobj_attrib_t car_mesh = {0};
	tinyobj_shape_t *car_shapes = NULL;
	u64 car_shape_count;
	tinyobj_material_t *car_materials = NULL;
	u64 car_material_count;

	// tinyobj_attrib_t city_mesh = {0};
	// tinyobj_shape_t *city_shapes;
	// u64 city_shape_count;
	// tinyobj_material_t *city_materials;
	// u64 city_material_count;

	tinyobj_parse_obj(&car_mesh, &car_shapes, &car_shape_count, &car_materials, &car_material_count, "../assets/cw1/car.obj", get_file_data, NULL, TINYOBJ_FLAG_TRIANGULATE);

	return 0;
}
```

`get_file_data`is the same as in viewer.c, I'm on using Windows and Visual Studio if that makes any different.

> Reading `car.obj` with `viewer` https://github.com/syoyo/tinyobjloader-c/tree/master/examples/viewer does not go into infinite loop.

the problem happened with the material, although pedantic to ask but could you check and see if the material file has been read? I don't have access to a linux machine to test `viewer.c` immediately.

**Comment by syoyo** [comment]
You can use WSL2. And `viewer` works well without issue on my WSL2 environment.

<img width="859" alt="Screenshot 2022-05-21 032742" src="https://user-images.githubusercontent.com/18676/169590425-433cc7a1-dede-46a5-bd12-0047da0f28e8.png">


Anyway, hashtable code is provided by a contributor, not me. So I don't know how reliable it is. 
You can contribute more reliable and robust hashtable implementation!

**Comment by syoyo** [comment]
BTW you should use `size_t`, not (your own?) `u64`.

```
u64 car_shape_count;
```
