### ISSUE TITLE
C89 compatibility is incorrect claim

### ISSUE THREAD

**Issue by slapin** [syoyo/tinyobjloader-c#6]
The code uses in-loop initializers (i.e. for int x...) and C++ comments,
so it is not pure C89 code. It is C99-style code.

**Comment by syoyo** [comment]
Hmm... Some contributed code uses C99 style. Will fix it soon(Your PR is always welcome, though)

**Comment by leok7v** [comment]
Just a suggestion maybe just change the claim to C99. It's 2018 and even Microsoft is switching to clang and gcc and both support C99 for a long time... It's actually easier to read and less error prone.

**Comment by syoyo** [comment]
I see. > It's actually easier to read and less error prone.

Even though I did some C99 -> C89 fix in this commit https://github.com/syoyo/tinyobjloader-c/commit/8daec4d18a28c1d0522ce16ee1e2c8d2795a135d , but it would be good time to move to C99

**Comment by nashidau** [comment]
Pull request sent to move to std-c99 for gcc/clang.

**Comment by nashidau** [comment]
This can be closed right?

**Comment by syoyo** [comment]
@nashidau Oh yes. closed via https://github.com/syoyo/tinyobjloader-c/pull/46
